version: '3.8'

services:
  server:
    image: fauria/vsftpd
    container_name: server
    ports:
      # - "21:21"
      - "30000-30009:30000-30009"
    environment:
      - FTP_USER=ftpuser
      - FTP_PASSWORD=ftppass
    volumes:
      - /home/ascatama/Documents:/srv
    networks:
      - inquisitor

  client:
    image: jlesage/filezilla
    container_name: client
    ports:
      - "5800:5800"
    volumes:
      - ./storage:/storage:rw
    networks:
      - inquisitor

  inquisitor:
    build: .
    image: inquisitor
    container_name: inquisitor
    networks:
      - inquisitor

networks:
  inquisitor:
