version: '3.8'

services:
  inquisitor:
    build: .
    image: inquisitor
    container_name: inquisitor
    volumes:
      - ./inquisitor.py:/app/inquisitor.py
    networks:
      - inquisitor
    # privileged: true
    # cap_add:
    #   - NET_RAW
    #   - NET_ADMIN


  server:
    # image: fauria/vsftpd
    image: delfer/alpine-ftp-server
    container_name: server
    ports:
      - "21000-21010:21000-21010"
    environment:
      - USERS=one|Qwertyuiop1234
      # - FTP_USER=ftpuser
      # - FTP_PASSWORD=ftppass
    volumes:
      - ./one:/ftp/one
    networks:
      - inquisitor

  client:
    image: jlesage/filezilla
    container_name: client
    ports:
      - "5800:5800"
    volumes:
      - ./storage:/storage:rw
    networks:
      - inquisitor


networks:
  inquisitor:
