version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./index.html:/var/www/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./torrc:/etc/tor/torrc
    expose:
      - "8080"
    command: /bin/sh -c "service tor start && nginx -g 'daemon off;'"
