version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "4343:4343"
    volumes:
      - ./index.html:/var/www/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./sshd_config:/etc/ssh/sshd_config 
      - ./torrc:/etc/tor/torrc
    # expose:
    #   - "8080"
    # execute when the container is launch
    # command: /bin/sh -c "service tor start && nginx -g 'daemon off;'"
