version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
      - "4242:4242"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./sshd_config:/etc/ssh/sshd_config
      - ./torrc:/etc/tor/torrc
    restart: unless-stopped
