#!/usr/bin/env python3

import argparse

if __name__ == "__main__":

    parser = argparse.ArgumentParser(
                    prog='Vaccine',
                    description='vaccine which allows you to perform an SQL injection by providing a url as parameter.',
                    epilog='42 Cybersecurity')

    parser.add_argument('URL', type=str, help='The URL of the website to perform SQL injection')
    parser.add_argument('-o', type=str, default="archive", help='Archive file, if not specified it will be stored in a default one.')
    parser.add_argument('-X', type=str, default="GET", help='Type of request, if not specified GET will be used.')

    args = parser.parse_args()

    print(args)
