#!/usr/bin/env python3

import os
import sys # to handle command line-arguments
from PIL import Image
from PIL.ExifTags import TAGS # to open img and extract EXIF data

def display_image_metadata(img_path):

    try:
        with Image.open(img_path) as img: # with ensure the ressource will be closed
            print(f"Metadata for {img_path}:")
            print(f"Format: {img.format}")
            print(f"Size: {img.size}")
            print(f"Mode: {img.mode}")

            print()
            exif_data = img._getexif()
            if exif_data:
                print(" EXIF Data : ")
                for tag, value in exif_data.items():
                    tag_name = TAGS.get(tag, tag)
                    print(f" -{tag_name}: {value}")
            else:
                print("No EXIF data found.")
        
    except Exception as e:
        print(f"Error processing {img_path}: {e}")

if __name__ == '__main__' :

    if len(sys.argv) < 2:
        print("Usage: scorpion FILE1 [FILE2 ...]")
        sys.exit(1)

    supported_extensions = {'.jpg', '.jpeg', '.png', '.gif', '.bmp'}
    files = sys.argv[1:] # all nothing name of program

    for file in files:
        if os.path.splitext(file)[1].lower() in supported_extensions:
            display_image_metadata(file)
        else:
            print(f"Unsupported file format: {file}")
